# Generated by Django 4.1.3 on 2023-01-19 04:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockParameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "money",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "start_year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1980),
                            django.core.validators.MaxValueValidator(2022),
                        ]
                    ),
                ),
                (
                    "end_year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1980),
                            django.core.validators.MaxValueValidator(2022),
                        ]
                    ),
                ),
                (
                    "index",
                    models.CharField(
                        choices=[
                            ("s&p", "S&P 500"),
                            ("djia", "DJIA"),
                            ("nasdaq", "NASDAQ"),
                        ],
                        default="s&p",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockTicker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=5)),
                ("first_trade_year", models.IntegerField()),
                ("company_name", models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="StockPriceData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("initial_invested_amount", models.IntegerField()),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.stockticker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_date", models.DateField()),
                ("price", models.IntegerField(default=0)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.stockticker",
                    ),
                ),
            ],
        ),
    ]
