# Generated by Django 4.1.3 on 2023-01-19 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockpricedata",
            name="stock",
        ),
        migrations.DeleteModel(
            name="PriceHistory",
        ),
        migrations.DeleteModel(
            name="StockPriceData",
        ),
    ]
