# Generated by Django 4.1.3 on 2023-01-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_stockpricedata_stock_delete_pricehistory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockparameters",
            name="end_year",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="stockparameters",
            name="start_year",
            field=models.DateField(),
        ),
    ]
