# Generated by Django 4.1.3 on 2023-02-19 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_rename_end_year_stockparameters_end_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockticker",
            old_name="first_trade_year",
            new_name="first_trade_date",
        ),
    ]
